// Code generated by "stringer -type=move"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[up-0]
	_ = x[down-1]
	_ = x[left-2]
	_ = x[right-3]
}

const _move_name = "updownleftright"

var _move_index = [...]uint8{0, 2, 6, 10, 15}

func (i move) String() string {
	if i < 0 || i >= move(len(_move_index)-1) {
		return "move(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _move_name[_move_index[i]:_move_index[i+1]]
}
